### ISSUE TITLE
Is PHP >= 5.6.0 necessary?

### ISSUE THREAD

**Issue by vercotux** [hautelook/phpass#12]
I am trying to use this library on Ubuntu Trusty, which comes with PHP no higher than 5.5.9, so the installation of this package is blocked by composer. Is there a reason the requirement is 5.6.0 or could it be lowered slightly?

According to [Openwall](http://openwall.com/phpass/) phpass should work fine with PHP 5.3.0 and above (or even as low as PHP 3.0.18 with fallbacks).

**Comment by hjr3** [comment]
It requires `php 5 >= 5.6.0` because we use http://php.net/hash_equals to prevent timing attacks. You can use https://github.com/hautelook/phpass/tree/0.3.4 which only requires `php 5.3.3`.

I will update the README to make this more clear.

**Comment by vercotux** [comment]
Why not use a [fallback hash_equals()](https://php.net/manual/en/function.hash-equals.php#115635) ?

**Comment by hjr3** [comment]
@vercotux see the discussion here https://github.com/hautelook/phpass/pull/11

**Comment by vercotux** [comment]
>The goal of this bundle was to make it easier for people to use PHPass in their modern PHP code.

This could not be further from the truth. This bundle is a joke. Hope somebody makes a proper fork. What a waste of time.

**Comment by hjr3** [comment]
@vercotux the original version is at http://openwall.com/phpass/ if that works better for you.
