### ISSUE TITLE
Document use of `random_bytes` hook before making 1.1.0 release

### ISSUE THREAD

**Issue by hjr3** [hautelook/phpass#15]

**Comment by KorvinSzanto** [comment]
Is there a way I can help with this? We're hoping to include 1.1.0 in our next release.

**Comment by hjr3** [comment]
@KorvinSzanto i have a PR waiting once github is fixed 😄

**Comment by hjr3** [comment]
Fixed in https://github.com/hautelook/phpass/pull/16

**Comment by hjr3** [comment]
@KorvinSzanto https://github.com/hautelook/phpass/tree/1.1.0

**Comment by KorvinSzanto** [comment]
@hjr3 I just realized I'm an idiot 🤕 We depend on 0.3.4 since we're 5.5.9+. Sorry for rushing you here, I guess we'll need to continue wrapping for the time being.

**Comment by hjr3** [comment]
@KorvinSzanto if i backport the change to the `0.3` branch and make `0.3.5` would that work for you?

**Comment by KorvinSzanto** [comment]
Definitely

**Comment by hjr3** [comment]
@KorvinSzanto https://github.com/hautelook/phpass/releases/tag/0.3.5

**Comment by KorvinSzanto** [comment]
:+1: thanks!
